[book]
authors = ["Chris Walquist"]
language = "en"
multilingual = false
src = "src"
title = "Git Basics - Collaborating With Git"

[output.html]
default-theme = "rust"

[build]
build-dir = "../docs"
